title_primary: '银之匙' # the bigger text
title_secondary: '不要变成记录在本子上的人生' # the smaller text
keywords:

twitter: Samlldevel
rss: atom.xml
weibo: #username/id
instagram: #username
github: Samlldevel

# Choose the comment service according to your need.
# Please do not use the two services at the same time.
livere: # [data-uid] on livere.com
disqus: # [short_name] on disqus.com
dove: # For fun ONLY. Set to true to 'disable' comments on your site.
valine: true

valine_appid: 'C5UQwaddmDNfGT2GyHq1RKN4-gzGzoHsz'
valine_appkey: 'nwu3U2sv3JcUcitnVTaO22GS'
valine_serverURLs: 'https://leancloud.pengliang.online'
avatar: 'robohash'
# Set true to show the page indicator.
showPageCount: true

# Set true to show category or tags behind post titles
showCategories: true
showTags: true

# Color scheme
themeStyle: light # light/dark
